In [2]:
import numpy as np
a = [1,45,78,90]
type(a)
b = np.array(a)
b

array([ 1, 45, 78, 90])

In [3]:
a = [[1,2,3,4],[4,5,6,7],[7,8,9,5]]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 5]]

In [5]:
b = np.array(a)
b

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 5]])

In [6]:
print('total rows and colcumn:', b.shape)
print('total elements:', b.size)
print('total dimension:', b.ndim)

total rows and colcumn: (3, 4)
total elements: 12
total dimension: 2


In [9]:
#zeros
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#ones
a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#eye
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
a = np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
#diag()
a = np.diag([1,12,13,45,2])
a

array([[ 1,  0,  0,  0,  0],
       [ 0, 12,  0,  0,  0],
       [ 0,  0, 13,  0,  0],
       [ 0,  0,  0, 45,  0],
       [ 0,  0,  0,  0,  2]])

In [19]:
#randint
a = np.random.randint(0,7,2)
a

array([4, 3], dtype=int32)

In [20]:
a = np.random.rand(3)
a

array([0.334158  , 0.74014821, 0.30124887])

In [4]:

a = np.random.seed(1,10,2)
a

TypeError: seed() takes at most 1 positional argument (3 given)

In [6]:
# view and copy
a = np.array([11,12,13,14,15,16,17,18,19,20])
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
b = a[3:6]
b

array([14, 15, 16])

In [8]:
b[:] = 0
a

array([11, 12, 13,  0,  0,  0, 17, 18, 19, 20])

In [10]:
a = np.array([11,12,13,14,15,16,17,18,19,20])
b = a[3:6].copy()
b[:] = 0
b

array([0, 0, 0])

In [11]:
a

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])