In [1]:
import numpy as np


In [2]:
#operations And Array


In [4]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [6]:
b = a>10
b

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [7]:
a[b]

array([11, 12, 13, 14, 15])

In [8]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [9]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [11]:
#RESHAPING ARRAY
#n(rows )*n(col) = total elements

In [16]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [18]:
b = np.arange(11,15).reshape(2,2)
b

array([[11, 12],
       [13, 14]])

In [19]:
a+b

array([[12, 14],
       [16, 18]])

In [20]:
a-b

array([[-10, -10],
       [-10, -10]])

In [21]:
a/b

array([[0.09090909, 0.16666667],
       [0.23076923, 0.28571429]])

In [22]:
a.dot(b)

array([[37, 40],
       [85, 92]])

In [23]:
a**2

array([[ 1,  4],
       [ 9, 16]])

In [24]:
a**3

array([[ 1,  8],
       [27, 64]])

In [25]:
#linspace() ----> it will return the same gap btw values in an range

In [27]:
a = np.linspace(1,5,10)
a

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [28]:
#unique : it will provide an arry inn which it will return 3 array
#arr
#return_index
#return_counts

In [29]:
a = np.array([1,2,1,1,1,2,2,3,4,5,6,6])

In [31]:
np.unique(a, return_index=True, return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  7,  8,  9, 10]),
 array([4, 3, 1, 1, 1, 2]))

In [33]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.sum(a)

np.int64(45)

In [35]:
np.sum(a ,axis = 0)

array([12, 15, 18])

In [36]:
np.sum(a ,axis = 1)

array([ 6, 15, 24])

In [37]:
#HSTACK AND VSTACK

In [ ]:
a = np.arange(1,5)
b = np.arange(5,9)
c = np.arange(9,13)

In [43]:
np.hstack((a,b,c))

NameError: name 'c' is not defined